services:

  frontend:
    image: smeif-front
    build:
      context: ./SMEIF-FRONT
      dockerfile: Dockerfile  
    container_name: smeif-front
    ports:
      - "3009:3000"
    networks:
      - smeif-network
    depends_on:
      - api

  api:
    image: smeif-api
    build:
      context: ./SMEIF-API
      dockerfile: Dockerfile  
    container_name: smeif-api
    ports:
      - "5009:5000"
    networks:
      - smeif-network
    depends_on:
      - database
    env_file:
      - ./SMEIF-API/.env
    volumes:
      - ./SMEIF-API:/api` # Bind mount para desenvolvimento

  database:
    container_name: smeif-database
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5439:5432"
    networks:
      - smeif-network
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: always   

networks:
  smeif-network:
    driver: bridge

volumes:
  db_volume: